fix: define packages witin setup.py
Otherwise, creating an sdist with eg. "python3 setup.py sdist" fails
because it's not clear for setuptools which of the directories
actually contains the python code.

This fixes:

$ python3 setup.py sdist
error: Multiple top-level packages discovered in a flat-layout: \
    ['etc', 'agent', 'packaging'].